# 예외처리
프로그래머가 계획한 시나리오를 벗어나는 사건을 예외라고 한다. <br/>
적절하지 않은 매개변수로 인해 정의되지 않은 동작을 수행하는 대신, 예외를 발생시켜 상위코드에서 처리할 수 있도록 한다. <br/>
단, 발생한 예외를 어떤 코드에서도 처리하지 않으면 ```CLR```에게까지 예외를 던지게 되는데, 이것은 처리되지 않은 예외가 된다. <br/>
처리되지 않은 예외는 해당 내용을 사용자에게 출력한 후, 프로그램을 강제로 종료한다.

## try
예외가 발생할 수 있는 함수를 시도한다. <br/>
```try```절 내에서 예외가 발생한다면, ```try```절의 코드진행을 중단하고# 예외처리
프로그래머가 계획한 시나리오를 벗어나는 사건을 예외라고 한다. <br/>
적절하지 않은 매개변수로 인해 정의되지 않은 동작을 수행하는 대신, 예외를 발생시켜 상위코드에서 처리할 수 있도록 한다. <br/>
단, 발생한 예외를 어떤 코드에서도 처리하지 않으면 ```CLR```에게까지 예외를 던지게 되는데, 이것은 처리되지 않은 예외가 된다. <br/>
처리되지 않은 예외는 해당 내용을 사용자에게 출력한 후, 프로그램을 강제로 종료한다.

## try
예외가 발생할 수 있는 함수를 시도한다. <br/>
```try```절 내에서 예외가 발생한다면, ```try```절의 코드진행을 중단하고 이후 설명할 ```catch```절에서 예외를 처리하게 된다. <br/>

## catch
```try```절에서 수행한 코드 중에 예외가 발생한다면, 적절한 ```catch```절에서 예외를 받아 처리하게 된다. <br/>
```try```절에서 발생한 예외객체와 ```catch```절의 예외객체는 형식이 일치해야한다. <br/>
일치하는 ```catch```절이 없다면 던져진 예외는 처리되지 않은 예외가 된다.

```cs
try
{
  // 수행할 코드
}
catch (예외 객체 이름)
{
  // 예외 처리
}
```

## throw
예외를 발생시킨다. <br/>
메소드 내에서 특정 조건을 만족하여 프로그래머가 계획한 시나리오를 벗어났을 때, 예외를 발생시키고 ```try-catch```문에서 받아낸다. <br/>

```cs
try
{
  throw new Exception("");
}
catch (Exception e)
{
  // 처리
}
```

### throw 식
보통 ```throw```문을 통해 예외를 던지게 되지만, ```throw```식으로도 사용할 수 있다. <br/>
```cs
int? a = null; // a는 nullable 형식이며, null이다.
int b = a ?? throw new ArgumentNullException(); // a가 null이 아니라면 a를 대입하고, null이라면 예외를 던진다.
```

## finally
```try```절에서 예외가 발생하면 ```try```절의 실행은 중단된다. <br/>
```try```절의 마지막에서 ```DB Connection```을 닫는 동작을 수행하게 만들었다면, 예외가 발생할 때마다 커넥션이 줄어 문제가 될 수 있다. <br/>
```finally```절은 ```try```절이 수행되었다면, 예외의 발생 여부와 관계없이 반드시 실행된다. <br/>

```cs
try
{
  dbconn.Open();
  // ...
}
catch (XXXException e)
{
  // ...
}
finally
{
  dbconn.Close();
}
```

## 사용자 정의 예외
C++과 마찬가지로 C#도 예외를 정의하여 사용할 수 있다. <br/>
모든 예외는 ```System.Exception```클래스로부터 파생된다. <br/>
그리고 ```catch```절에서 부모예외클래스를 처리하도록 구현한다면, 자식예외객체도 해당 ```catch```절에서 처리될 수 있다. <br/>
자식예외를 더 구체적인 로직으로 처리하고 싶다면, 반드시 자식예외클래스를 먼저 처리하도록 구현해야한다. <br/>
(그리고 ```catch```절은 하나만 진입한다.)

## 예외 필터
C# 6.0부터 ```catch```절이 받아들일 예외 객체에 제약사항을 명시할 수 있는 기능인 예외필터가 추가되었다. <br/>
```cs
class FilterableException : Exception
{
  public int ErrorNo {get;set;}
}

try
{
  int num = GetNumber();
  if(num < 0 || num >10)
  {
    throw new FilterableException() {ErrorNo = num};
  }
}
catch (FilterableException e) when (e.ErrorNo < 0) // e.ErrorNo가 0보다 작은 경우에만 해당 catch절로 진입한다.
{
  // 처리
}
catch (FilterableException e)
{
  // 처리
}
```
